development:
  products_api_url: 'http://localhost:3003/api/v1/'
  customer_api_url: 'http://localhost:3002/api/v1/clients'
  payments_api_url: 'http://localhost:3001/api/v1/'
test:
  products_api_url: 'https://www.seek4k.com.br/v1'
  customer_api_url: 'https://www.seek4k.com.br/v1/customers'
  payments_api_url: 'https://www.seek4k.com.br/v1'
production:
  products_api_url: 'https://www.seek4k.com.br/v1'
  customer_api_url: 'https://www.seek4k.com.br/v1/customers'
  payments_api_url: 'https://www.seek4k.com.br/v1'
